# SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE AS 중성화
# FROM ANIMAL_INS
# WHERE SEX_UPON_INTAKE = 'Neutered' or 'Spayed'
# ORDER BY ANIMAL_ID

SELECT 
  ANIMAL_ID, 
  NAME,
  CASE 
    WHEN SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
    ELSE 'X'
  END AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;